+ '[' -z '' ']'
+ case "$-" in
+ __lmod_vx=x
+ '[' -n x ']'
+ set +x
Shell debugging temporarily silenced: export LMOD_SH_DBG_ON=1 for this output (/usr/share/lmod/lmod/init/bash)
Shell debugging restarted
+ unset __lmod_vx
+ CUPATH=/home/harms/working/copper/copper/build
+ LOGDIR=/home/harms/copper-logs/713354
+ mkdir -p /home/harms/copper-logs/713354
+ WCOLL=/var/spool/pbs/aux/713354.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov
+ pdsh mkdir -p /tmp/copper
+ read -r -d '' CMD
+ WCOLL=/var/spool/pbs/aux/713354.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov
+ pdsh -t 60 /home/harms/working/copper/copper/build/cu_fuse -tpath / -vpath /tmp/copper -log_level 5 -log_type file -log_output_dir /home/harms/copper-logs/713354 -es 2 -nf /var/spool/pbs/aux/713354.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov /tmp/copper
++ cat /var/spool/pbs/aux/713354.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov
++ wc -l
+ nodes=512
+ sleep 60
+ echo 'Launch Baseline Nodes:512'
Launch Baseline Nodes:512
+ mpiexec -n 6144 -ppn 12 sleep 1

real	0m1.532s
user	0m0.006s
sys	0m0.007s
+ echo 'First Nodes:512 Python:12 ES:1 fcores:1 total:2'
First Nodes:512 Python:12 ES:1 fcores:1 total:2
+ mpiexec -n 6144 -ppn 12 --genvall --genv=PYTHONPATH=/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages --cpu-bind=list:52-103 /soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/bin/python3 -c 'import numpy; print(numpy.__file__)'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/editline'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
x4712c0s7b0n0.hostmgmt2712.cm.aurora.alcf.anl.gov: rank 3708 exited with code 1
x4712c0s7b0n0.hostmgmt2712.cm.aurora.alcf.anl.gov: rank 3710 died from signal 15

real	0m4.842s
user	0m0.058s
sys	0m0.035s
+ echo 'Cached Nodes:512 Python:12 ES:1 fcores:1 total:2'
Cached Nodes:512 Python:12 ES:1 fcores:1 total:2
+ mpiexec -n 6144 -ppn 12 --genvall --genv=PYTHONPATH=/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages --cpu-bind=list:52-103 /soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/bin/python3 -c 'import numpy; print(numpy.__file__)'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
ConnectionAbortedError: [Errno 103] Software caused connection abort: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/editline'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/editline'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Error in usercustomize; set PYTHONVERBOSE for traceback:
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages'
x4710c0s0b0n0.hostmgmt2710.cm.aurora.alcf.anl.gov: rank 2962 exited with code 1
x4710c0s0b0n0.hostmgmt2710.cm.aurora.alcf.anl.gov: rank 2952 died from signal 15

real	0m5.423s
user	0m0.053s
sys	0m0.035s
+ WCOLL=/var/spool/pbs/aux/713354.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov
+ pdsh -t 60 fusermount3 -u /tmp/copper
