Cached Python:12 ES:1 fcores:1 total:2

real	0m7.762s
user	0m0.002s
sys	0m0.007s
/var/spool/pbs/mom_priv/jobs/707997.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov.SC: line 31: 85527 Terminated              numactl --physcpubind="${list}" $CUPATH/cu_fuse -tpath / -vpath /tmp/copper -log_level 6 -log_type file -log_output_dir /tmp/copper-logs -es ${es} -f /tmp/copper
malloc_consolidate(): invalid chunk size
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 141, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 141, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 141, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 141, in <module>
/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py:139: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 141, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 141, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 141, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 141, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 141, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 139, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 139, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/_distributor_init.py", line 13, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/core/__init__.py", line 78, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/core/__init__.py", line 78, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/core/__init__.py", line 82, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/_distributor_init.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 139, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/_distributor_init.py", line 13, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/core/__init__.py", line 78, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/core/__init__.py", line 78, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/core/__init__.py", line 78, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/core/__init__.py", line 78, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/mkl/__init__.py", line 54, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/core/multiarray.py'
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/core/records.py'
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/core/records.py'
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/core'
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/core/records.py'
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/core/records.py'
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy'
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/mkl/__init__.py", line 54, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/mkl'
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/core/records.py'
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/core/records.py'
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/mkl/__init__.py", line 54, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/mkl'
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/mkl'
x4709c2s6b0n0.hostmgmt2709.cm.aurora.alcf.anl.gov: rank 7 exited with code 1
x4709c2s6b0n0.hostmgmt2709.cm.aurora.alcf.anl.gov: rank 2 died from signal 15
Cached Python:12 ES:1 fcores:2 total:3
/var/spool/pbs/mom_priv/jobs/707997.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov.SC: line 31: 86080 Aborted                 numactl --physcpubind="${list}" $CUPATH/cu_fuse -tpath / -vpath /tmp/copper -log_level 6 -log_type file -log_output_dir /tmp/copper-logs -es ${es} -f /tmp/copper

real	0m0.506s
user	0m30.328s
sys	0m32.168s
/var/spool/pbs/mom_priv/jobs/707997.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov.SC: line 60: kill: (86080) - No such process
Cached Python:12 ES:1 fcores:4 total:5

real	0m2.453s
user	0m0.003s
sys	0m0.006s
/var/spool/pbs/mom_priv/jobs/707997.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov.SC: line 31: 86170 Terminated              numactl --physcpubind="${list}" $CUPATH/cu_fuse -tpath / -vpath /tmp/copper -log_level 6 -log_type file -log_output_dir /tmp/copper-logs -es ${es} -f /tmp/copper
Cached Python:12 ES:1 fcores:8 total:9

real	0m5.759s
user	0m0.007s
sys	0m0.002s
/var/spool/pbs/mom_priv/jobs/707997.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov.SC: line 31: 86771 Terminated              numactl --physcpubind="${list}" $CUPATH/cu_fuse -tpath / -vpath /tmp/copper -log_level 6 -log_type file -log_output_dir /tmp/copper-logs -es ${es} -f /tmp/copper
Cached Python:12 ES:2 fcores:1 total:3

real	0m2.875s
user	0m0.003s
sys	0m0.006s
/var/spool/pbs/mom_priv/jobs/707997.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov.SC: line 31: 87585 Terminated              numactl --physcpubind="${list}" $CUPATH/cu_fuse -tpath / -vpath /tmp/copper -log_level 6 -log_type file -log_output_dir /tmp/copper-logs -es ${es} -f /tmp/copper
Cached Python:12 ES:2 fcores:2 total:4

real	0m2.292s
user	0m0.007s
sys	0m0.002s
/var/spool/pbs/mom_priv/jobs/707997.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov.SC: line 31: 88245 Terminated              numactl --physcpubind="${list}" $CUPATH/cu_fuse -tpath / -vpath /tmp/copper -log_level 6 -log_type file -log_output_dir /tmp/copper-logs -es ${es} -f /tmp/copper
Cached Python:12 ES:2 fcores:4 total:6

real	0m2.931s
user	0m0.000s
sys	0m0.008s
/var/spool/pbs/mom_priv/jobs/707997.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov.SC: line 31: 88765 Terminated              numactl --physcpubind="${list}" $CUPATH/cu_fuse -tpath / -vpath /tmp/copper -log_level 6 -log_type file -log_output_dir /tmp/copper-logs -es ${es} -f /tmp/copper
Cached Python:12 ES:2 fcores:8 total:10

real	0m5.465s
user	0m0.000s
sys	0m0.009s
/var/spool/pbs/mom_priv/jobs/707997.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov.SC: line 31: 89941 Terminated              numactl --physcpubind="${list}" $CUPATH/cu_fuse -tpath / -vpath /tmp/copper -log_level 6 -log_type file -log_output_dir /tmp/copper-logs -es ${es} -f /tmp/copper
double free or corruption (fasttop)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 144, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/__init__.py", line 40, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 144, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/__init__.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/_version.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 144, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/__init__.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/_version.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 144, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/__init__.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/_version.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 144, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/__init__.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/_version.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 144, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/__init__.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/_version.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 144, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/__init__.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/_version.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 144, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/__init__.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/_version.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 144, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/__init__.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/_version.py'
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/_version.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 144, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/__init__.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/_version.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 144, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/__init__.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/_version.py'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/__init__.py", line 144, in <module>
  File "/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/__init__.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/copper/soft/compilers/oneapi/2023.12.15.001/oneapi/intelpython/python3.9/lib/python3.9/site-packages/numpy/lib/_version.py'
x4709c2s6b0n0.hostmgmt2709.cm.aurora.alcf.anl.gov: rank 11 exited with code 1
Cached Python:12 ES:4 fcores:1 total:5
/var/spool/pbs/mom_priv/jobs/707997.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov.SC: line 31: 90845 Aborted                 numactl --physcpubind="${list}" $CUPATH/cu_fuse -tpath / -vpath /tmp/copper -log_level 6 -log_type file -log_output_dir /tmp/copper-logs -es ${es} -f /tmp/copper

real	0m0.467s
user	0m33.404s
sys	0m33.379s
/var/spool/pbs/mom_priv/jobs/707997.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov.SC: line 60: kill: (90845) - No such process
Cached Python:12 ES:4 fcores:2 total:6

real	0m3.073s
user	0m0.002s
sys	0m0.007s
/var/spool/pbs/mom_priv/jobs/707997.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov.SC: line 31: 91179 Terminated              numactl --physcpubind="${list}" $CUPATH/cu_fuse -tpath / -vpath /tmp/copper -log_level 6 -log_type file -log_output_dir /tmp/copper-logs -es ${es} -f /tmp/copper
x4709c2s6b0n0.hostmgmt2709.cm.aurora.alcf.anl.gov: rank 7 died from signal 7
x4709c2s6b0n0.hostmgmt2709.cm.aurora.alcf.anl.gov: rank 2 died from signal 15
Cached Python:12 ES:4 fcores:4 total:8
/var/spool/pbs/mom_priv/jobs/707997.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov.SC: line 31: 92478 Segmentation fault      numactl --physcpubind="${list}" $CUPATH/cu_fuse -tpath / -vpath /tmp/copper -log_level 6 -log_type file -log_output_dir /tmp/copper-logs -es ${es} -f /tmp/copper

real	0m0.536s
user	0m38.457s
sys	0m42.046s
/var/spool/pbs/mom_priv/jobs/707997.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov.SC: line 60: kill: (92478) - No such process
x4709c2s6b0n0.hostmgmt2709.cm.aurora.alcf.anl.gov: rank 9 died from signal 7
Cached Python:12 ES:4 fcores:8 total:12
/var/spool/pbs/mom_priv/jobs/707997.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov.SC: line 31: 92959 Segmentation fault      numactl --physcpubind="${list}" $CUPATH/cu_fuse -tpath / -vpath /tmp/copper -log_level 6 -log_type file -log_output_dir /tmp/copper-logs -es ${es} -f /tmp/copper

real	0m0.467s
user	0m38.995s
sys	0m57.136s
/var/spool/pbs/mom_priv/jobs/707997.aurora-pbs-0001.hostmgmt.cm.aurora.alcf.anl.gov.SC: line 60: kill: (92959) - No such process
